# Site settings
title: Max Kohler
description: "Max Kohler is a graphic designer based in London."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maxkoehler.com" # the base hostname & protocol for your site
twitter_username: maxakohler

# Build settings
markdown: kramdown
exclude: ["node_modules", "aws-keys.json", "package.json", "gruntfile.js", ".sass-cache", ".git"]
permalink: /:year/:title/
