# Site settings
title: Max Koehler
description: I’m Max Koehler. This is the story of me trying to become a graphic designer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maxkoehler.com" # the base hostname & protocol for your site
twitter_username: awesomephant

# Build settings
markdown: kramdown
exclude: ["node_modules", "aws-keys.json", "package.json", "gruntfile.js", ".sass-cache", ".git"]
permalink: /:year/:title/
