# Site settings
title: Max Koehler
description: > # this means to ignore newlines until "baseurl:"
 WThis is the story of me trying to become a graphic designer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: awesomephant

# Build settings
markdown: kramdown
exclude: ["node_modules"]
permalink: /:year/:title/